[project]
name = "agrisim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rahul Bavaliya", email = "60642504+rahul-bavaliya@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "celery>=5.6.3",
    "fastapi[standard]>=0.141.1",
    "geoalchemy2>=0.20.0",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
agrisim = "agrisim:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
