"""add soil_states table

Revision ID: 5ff554e6c3f5
Revises: 8b647970333a
Create Date: 2026-09-01 22:40:42.208255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff554e6c3f5'
down_revision: Union[str, Sequence[str], None] = '8b647970333a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('soil_moisture_mm', sa.Float(), nullable=False),
    sa.Column('field_capacity_mm', sa.Float(), nullable=False),
    sa.Column('wilting_point_mm', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_states_field_id'), 'soil_states', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_states_field_id'), table_name='soil_states')
    op.drop_table('soil_states')
    # ### end Alembic commands ###
